config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  
  get 'dashboard/index'

  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  get 'users/dashboard'

  resources :sessions, only: [:new, :create]
  get '/logout', controller: 'sessions', action: 'destroy'

  resources :bookings

  resources :games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
require 'cost_calculator'

class Booking < ApplicationRecord
  belongs_to :user

  before_save do |booking|
    cost = CostCalculator.new(booking)
    self.cost = cost.calculate
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :games
  has_secure_password
  validates :username, uniqueness: true
  validates :email, uniqueness: { message: 'already registered' }

  def email=(value)
    value = value.strip.downcase
    write_attribute :email, value
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  private

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(user_id: session[:user_id],
                          arrival: params[:booking][:arrival],
                          departure: params[:booking][:departure],
                          sps: params[:booking][:sps],
                          family: params[:booking][:family],
                          assistance: params[:booking][:assistance],
                          donation: params[:booking][:donation])
    if @booking.save
      redirect_to bookings_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to bookings_url
    else
      render 'edit'
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_url
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:arrival, :departure, :sps, :family, :assistance, :donation)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if session[:user_id] != nil
      @bookings = Booking.where(["user_id = #{session[:user_id]}"])
      @games = Game.where(["user_id = #{session[:user_id]}"])
    else
      redirect_to new_session_path
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def show
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(user_id: session[:user_id],
                    title: params[:game][:title],
                    game_system: params[:game][:game_system],
                    description: params[:game][:description],
                    min_players: params[:game][:min_players],
                    max_players: params[:game][:max_players],
                    pref_when: params[:game][:pref_when],
                    desired_players: params[:game][:desired_players],
                    campaign: params[:game][:campaign],
                    game_duration_hours: params[:game][:game_duration_hours],)
    if @game.save
      redirect_to games_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @game.update(game_params)
      redirect_to games_url
    else
      render 'edit'
    end
  end

  def destroy
    @game.destroy
    redirect_to games_url
  end

  private

  def find_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:title, :game_system, :description, :min_players,
                                :max_players, :pref_when, :desired_players,
                                :campaign, :game_duration_hours)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'Signed in successfully'
      redirect_to root_url
    else
      flash.now[:alert] = 'Invalid login details'
      render 'new'
    end
  end

  def destroy
    session.clear
    flash[:notice] = 'Successfully signed out'
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'Successfully signed up'
      redirect_to new_session_url
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/_form.html.erb
<div class="card mx-auto text-center px-4 pt-4 pb-3 mt-5" style="width: 375px;">
  <%= form_for @booking do |f| %>
    <%= f.label :arrival, 'Arrival Date' %>
    <%= f.date_field :arrival, class: "form-control mb-3" %>
    <%= f.label :departure, 'Departure Date' %>
    <%= f.date_field :departure, class: "form-control mb-3" %>
    <%= f.label :sps, 'Single Person Supplement?' %>
    <%= f.check_box :sps, class: "form-control mb-3" %>
    <%= f.label :family, 'Family Room?' %>
    <%= f.check_box :family, class: "form-control mb-3" %>
    <%= f.label :assistance, 'Claim discount from assistance fund' %>
    <%= f.check_box :assistance, class: "form-control mb-3" %>
    <%= f.label :donation, 'Make a donation to assistance fund (£)' %>
    <%= f.number_field :donation, class: "form-control mb-3" %>
    <%= f.submit 'Submit', class: "btn btn-success" %>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<h1 class="text-center" style="font-weight: lighter;"> Edit booking </h1>

<%= render "form", booking: @booking %>

app/views/bookings/index.html.erb
<h1 class="text-center" style="font-weight: lighter;"> My bookings </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Event</th>
      <th scope="col">Arrival Date</th>
      <th scope="col">Departure Date</th>
      <th scope="col">Single Person Supplement</th>
      <th scope="col">Family Room</th>
      <th scope="col">Assistance Fund</th>
      <th scope="col">Donation</th>
      <th scope="col">Total Cost (£)</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.reverse.each do |booking| %>
      <% if booking.user == current_user %>
      <tr>
        <td> (to follow) </td>
        <td><%= booking.arrival.strftime('%d/%m/%Y') %></td>
        <td><%= booking.departure.strftime('%d/%m/%Y') %></td>
        <td><%= check_box_tag :sps, "1", booking.sps, disabled: true %></td>
        <td><%= check_box_tag :family, "1", booking.family, disabled: true %></td>
        <td><%= check_box_tag :assistance, "1", booking.assistance, disabled: true %></td>
        <td><%= booking.donation %></td>
        <td><%= booking.cost / 100 %></td>
        <td>
          <%= link_to "Edit", edit_booking_path(booking) %>
          <%= link_to "Delete", booking_path(booking), method: :delete, data: { confirm: "Are you sure?"} %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<h1 class="text-center" style="font-weight: lighter;"> Make a booking </h1>

<%= render "form", booking: @booking %>

app/views/bookings/show.html.erb
<h1 class="text-center" style="font-weight: lighter;">Booking details</h1>
<div class="card my-5 mx-auto" style="width: 80%;" id="booking-container">
  <span class="card-header">
    <% if @booking.user == current_user %>
    <span style="float: right;">
      <%= link_to "Edit", edit_booking_path(@booking) %>
      <%= link_to "Delete", booking_path(@booking), method: :delete, data: { confirm: "Are you sure?"} %>
    </span>
    <% end %>
  </span>
  <span class="d-inline-flex">
    Arrival date: <p class="text-justify m-2"><%= @booking.arrival %></p>
    Departure date: <p class="text-justify m-2"><%= @booking.departure %></p>
  </span>
</div>

app/views/dashboard/index.html.erb
<h1 class="text-center" style="font-weight: lighter;"> Callacon </h1>
<h2 class="text-center" style="font-weight: lighter;"> My Bookings </h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Event</th>
      <th scope="col">Arrival Date</th>
      <th scope="col">Departure Date</th>
      <th scope="col">Single Person Supplement</th>
      <th scope="col">Family Room</th>
      <th scope="col">Assistance Fund Claim</th>
      <th scope="col">Donation</th>
      <th scope="col">Total Cost (£)</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.reverse.each do |booking| %>
      <% if booking.user == current_user %>
      <tr>
        <td> (to follow) </td>
        <td><%= booking.arrival.strftime('%d/%m/%Y') %></td>
        <td><%= booking.departure.strftime('%d/%m/%Y') %></td>
        <td><%= check_box_tag :sps, "1", booking.sps, disabled: true %></td>
        <td><%= check_box_tag :family, "1", booking.family, disabled: true %></td>
        <td><%= check_box_tag :assistance, "1", booking.assistance, disabled: true %></td>
        <td><%= booking.donation %></td>
        <td><%= booking.cost / 100 %></td>
        <td>
          <%= link_to "Edit", edit_booking_path(booking) %>
          <%= link_to "Delete", booking_path(booking), method: :delete, data: { confirm: "Are you sure?"} %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<h2 class="text-center" style="font-weight: lighter;"> My Games </h2>
<h3 class="text-center" style="font-weight: lighter;"> Games that I'm running </h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">GM</th>
      <th scope="col">Title</th>
      <th scope="col">System</th>
      <th scope="col">Description</th>
      <th scope="col">No. of players</th>
      <th scope="col">Campaign</th>
      <th scope="col">Duration (hours)</th>
      <th scope="col">Scheduled</th>
      <th scope="col">Desired players</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @games.reverse.each do |game| %>
      <% if game.user == current_user %>
      <tr>
        <td><%= game.user.first_name.capitalize %> <%= game.user.last_name.capitalize %></td>
        <td><%= game.title %></td>
        <td><%= game.game_system %></td>
        <td><%= game.description %></td>
        <td><%= game.min_players %> - <%= game.max_players %></td>
        <td><%= game.campaign %></td>
        <td><%= game.game_duration_hours %></td>
        <td><%= game.pref_when %></td>
        <td><%= game.desired_players %></td>
        <td>
          <%= link_to "Edit", edit_game_path(game) %>
          <%= link_to "Delete", game_path(game), method: :delete, data: { confirm: "Are you sure?"} %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<h3 class="text-center" style="font-weight: lighter;"> Games that I'm playing </h3>

app/views/games/_form.html.erb
<div class="card mx-auto text-center px-4 pt-4 pb-3 mt-5" style="width: 375px;">
  <%= form_for @game do |f| %>
    <%= f.label :title, 'Game title' %>
    <%= f.text_field :title, class: "form-control mb-3" %>
    <%= f.label :game_system, 'System' %>
    <%= f.text_field :game_system, class: "form-control mb-3" %>
    <%= f.label :description, 'Description' %>
    <%= f.text_field :description, class: "form-control mb-3" %>
    <%= f.label :min_players, 'Minimum number of players' %>
    <%= f.number_field :min_players, class: "form-control mb-3" %>
    <%= f.label :max_players, 'Maximum number of players' %>
    <%= f.number_field :max_players, class: "form-control mb-3" %>
    <%= f.label :pref_when, 'When would you prefer to run this game?' %>
    <%= f.text_field :pref_when, class: "form-control mb-3" %>
    <%= f.label :desired_players, 'Any essential players?' %>
    <%= f.text_field :desired_players, class: "form-control mb-3" %>
    <%= f.label :campaign, 'Is this game part of a campaign?' %>
    <%= f.text_field :campaign, class: "form-control mb-3" %>
    <%= f.label :game_duration_hours, 'Approximate game duration in hours' %>
    <%= f.number_field :game_duration_hours, class: "form-control mb-3" %>
    <%= f.submit 'Submit', class: "btn btn-success" %>
  <% end %>
</div>

app/views/games/index.html.erb
<h1 class="text-center" style="font-weight: lighter;"> Games </h1>
<h3 class="text-center" style="font-weight: lighter;"> Games that I'm running </h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">GM</th>
      <th scope="col">Title</th>
      <th scope="col">System</th>
      <th scope="col">Description</th>
      <th scope="col">No. of players</th>
      <th scope="col">Campaign</th>
      <th scope="col">Duration (hours)</th>
      <th scope="col">Scheduled</th>
      <th scope="col">Desired players</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @games.reverse.each do |game| %>
      <% if game.user == current_user %>
      <tr>
        <td><%= game.user.first_name.capitalize %> <%= game.user.last_name.capitalize %></td>
        <td><%= game.title %></td>
        <td><%= game.game_system %></td>
        <td><%= game.description %></td>
        <td><%= game.min_players %> - <%= game.max_players %></td>
        <td><%= game.campaign %></td>
        <td><%= game.game_duration_hours %></td>
        <td><%= game.pref_when %></td>
        <td><%= game.desired_players %></td>
        <td>
          <%= link_to "Edit", edit_game_path(game) %>
          <%= link_to "Delete", game_path(game), method: :delete, data: { confirm: "Are you sure?"} %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<h3 class="text-center" style="font-weight: lighter;"> All games </h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">GM</th>
      <th scope="col">Title</th>
      <th scope="col">System</th>
      <th scope="col">Description</th>
      <th scope="col">No. of players</th>
      <th scope="col">Campaign</th>
      <th scope="col">Duration (hours)</th>
      <th scope="col">Scheduled</th>
      <th scope="col">Desired players</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @games.reverse.each do |game| %>
      <tr>
        <td><%= game.user.first_name.capitalize %> <%= game.user.last_name.capitalize %></td>
        <td><%= game.title %></td>
        <td><%= game.game_system %></td>
        <td><%= game.description %></td>
        <td><%= game.min_players %> - <%= game.max_players %></td>
        <td><%= game.campaign %></td>
        <td><%= game.game_duration_hours %></td>
        <td><%= game.pref_when %></td>
        <td><%= game.desired_players %></td>
        <td>
          <% if game.user == current_user %>
            <%= link_to "Edit", edit_game_path(game) %>
            <%= link_to "Delete", game_path(game), method: :delete, data: { confirm: "Are you sure?"} %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<h1 class="text-center" style="font-weight: lighter;"> Add a game </h1>

<%= render "form", game: @game %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Callacon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    </head>

  <body>
  <nav class="navbar"> 
  <div>
    <% if current_user %>
    <span>
      Welcome, <%= current_user.username %>
      <a href="/" class="btn btn-primary ml-4 px-2 py-1">Home</a>
      <a href="/bookings" class="btn btn-primary ml-4 px-2 py-1">Bookings</a>
      <a href="/games" class="btn btn-primary ml-4 px-2 py-1">Games</a>
      <a href="/bookings/new" class="btn btn-primary ml-4 px-2 py-1">Add a booking</a>
      <a href="/games/new" class="btn btn-primary ml-4 px-2 py-1">Add a game</a>
      <%= link_to 'Sign Out', logout_path, class: "btn btn-danger ml-4" %> 
    </span> 
  <% else %>
    <%= link_to 'Sign Up', new_user_path, class: "btn btn-success mr-4" %>
    <%= link_to 'Sign In', new_session_path, class: "btn btn-primary" %>
  <% end %>
  </div>
</nav>

<% flash.each do |type, msg| %>
  <div class="alert alert-danger text-center mx-auto" role="alert" style="width: 98.38%;">
    <%= msg %>
  </div>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger text-center mx-auto" role="alert">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <div class="card mx-auto text-left px-4 pt-4 pb-3 mt-5" style="width: 375px;">
    <h3 class="card-title mb-3 text-center" style="font-weight: lighter;">Join our Family</h3>
    <%= f.text_field :username, placeholder: 'username', class: "form-control mb-3" %>
    <%= f.text_field :first_name, placeholder: 'first name', class: "form-control mb-3" %>
    <%= f.text_field :last_name, placeholder: 'last name', class: "form-control mb-3" %>
    <%= f.text_field :email, placeholder: 'email', class: "form-control mb-3" %>
    <%= f.password_field :password, placeholder: 'password', class: "form-control mb-3" %>
    <%= f.password_field :password_confirmation, placeholder: 'password confirmation', class: "form-control mb-3" %>
    <%= f.submit 'Sign Up', class: "btn btn-success" %>
  <% end %>
</div>